apiVersion: v1
kind: Service
metadata:
  name: fulfil-io-app
  labels:
    app: fulfil-io-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: fulfil-io-app
    tier: frontend
